# GRADLE JDK17 BASE IMAGE
FROM gradle:jdk17

# FAT JAR FILE from Project
ARG JAR_FILE=build/libs/TravSignOnService-fat.jar

# COPY JAR FILE FROM LOCAL TO DOCKER INSTANCE
COPY ${JAR_FILE} app.jar

# EXPOSE PORT AS 8080
EXPOSE 8080

# RUN THE APP JAR (START THE SERVER) WHEN CONTAINER IS RUNNING
ENTRYPOINT ["java", "-jar", "app.jar"]